# Description for social sharing and search engines.
description = "The tidyverse is an integrated collection of R packages designed to make data science fast, fluid, and fun."

# Enable copy-to-clipboard for all code?
# Can also enable by content section in _index.md file
copy_clipboard = true

# Default image for social sharing and search engines. Place image in `static/images/` folder and specify image name here.
sharing_image = "tidyverse-default.png"
twitter_image = "hex-tidyverse.png"

# Link custom CSS and JS assets
#   (relative to /static/css and /static/js respectively)
custom_css = ["tidyverse.css"]

# Define base hex url for index page (where the stickers link out to)
hex_base_url = ".tidyverse.org"

# Define main section as "blog"
mainSections = ["blog"]

# options for highlight.js (version, additional languages, and theme)
disable_highlightjs = "true"
highlightjsVersion = "9.11.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "markdown"]
highlightjsTheme = "github"

MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"

[footer]
    github_url = "https://github.com/tidyverse"
    twitter_url = "https://twitter.com/hashtag/rstats"
    # Enter a copyright notice to display in the site footer.
    # To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
    copyright = ""
    support = "The tidyverse is proudly supported by " # leave empty to remove support statement + RStudio logo

# leave blank in quotes for the default = true
# to turn off, set = false (no quotes)
[authors]
    show_list = "" # on list page, default is true
    show_single = "" # on single pages, default is true
    show_latest = "" # on bio, default is true
    label_latest = "" # on bio, default is "Latest"

# leave blank in quotes for the default = true
# to turn off, set = false (no quotes)
[events]
    link_archive = "" # default is true

# customize your site colors
# these colors get applied by layouts/partials/custom-site.css
# then, the layouts/partials/head_includes.html uses that partial
# the partial head_includes.html is called in the partial header.html everywhere!
[colors]
    text = "#1a1917"
    # Links
    link = "#38577f"
    link_hover = "#42709b"
    # Footer
    footer_primary = "#767381"
    footer_text = "#e3eef8"
    # Backgrounds
    background = "white"
    home_section_odd = "white"
    home_section_even = "#fdeba4"
    # Menu
    menu_primary = "#1a162d"
    menu_text = "#fff"
    menu_text_active = "#fff"
    menu_text_current = "#1a162d"
    menu_decorate_current = "none"
    menu_title = "#fff"
    menu_title_active = "#fdeba4"
    menu_box_hover = "#484557"
    menu_box_active = "#fff"
    # Tables
    header_background = "#dfe3eb"
    table_row_even = "#f7faff"
    table_row_odd = "#fff"

# Choose an accent font (article headers, h1, h2, table of contents etc.) with Google Fonts
[headers]
    # Import a Google font and styles, e.g. "@import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap');"
    # import = "@import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&display=swap');"
    # font-family = "Lato"

[capitalization]
# Make particular headers "uppercase" or "lowercase"
# set = false (no quotes) for normal text
    text_transform = false

#[accent_color]
    # Used for headers, so should be accessibility-friendly
    #color_primary = "#4254A7"
    #color_secondary = "#333850eb"

#[bullets]
    #color = "#f6b73c"

#[hexes]
    #thin_hex = true

[borders]
# For thin lines on Navbar, Table of contents divider, band borders, etc.
# To turn on, set = "1px"
# To turn off (default), set = false (no quotes)
    #thin_lines = "1px"

[event_stickies]
    straight = false
    text_color = "#404040"  # same as body text
    links = "#1a162d"
    border_color = "#a19ea936"
    background = "#eab0c41a"
