# Title of your site
title = "Tidyverse"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://www.tidyverse.org/"

# Name the theme folder in `themes/`.
theme = "hugo-tourmaline"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-115082821-1"


relativeurls = false
languageCode = "en-us"
description = "An opinionated collection of R packages designed for data science."
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
# below is critical for non-authors to show up in article listing
preserveTaxonomyNames = true
# uncomment the next line to disable listing authors
# disableKinds = ["taxonomyTerm"]

[permalinks]
    blog = "blog/:year/:month/:slug/"
    articles = "articles/:year/:month/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
  angledQuotes = false
  latexDashes = true
  extensions = ["backslashLineBreak"]
