# Title of your site
title: Tidyverse

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl: 'https://www.tidyverse.org/'

# Name the theme folder in `themes/`.
theme: hugo-tourmaline
# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics: UA-115082821-1

relativeurls: false
languageCode: en-us
description: An opinionated collection of R packages designed for data science.
disqusShortname: ''
ignoreFiles: ['\.Rmd$', '_files$', '_cache$', 'articles/.*']
# below is critical for non-authors to show up in article listing
preserveTaxonomyNames: true

permalinks:
  blog: 'blog/:year/:month/:slug/'
  articles: 'articles/:year/:month/:slug/'

taxonomies:
  category: categories
  tag: tags

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: pygments

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true
  twitter:
    enableDNT: true
    privacyEnhanced: true
